# Generated by Django 4.2.5 on 2023-09-10 23:21

from django.db import migrations, models
import lib2to3.fixes.fix_metaclass


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='FixMe', verbose_name=lib2to3.fixes.fix_metaclass.FixMetaclass),
            preserve_default=False,
        ),
    ]
